export const jackReacher = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/xHRabofjmMGoIV3mb6xgy4nwOcS.jpg',
      genre_ids: [27],
      id: 801071,
      original_language: 'en',
      original_title: 'The Jack in the Box: Awakening',
      overview:
        'When a vintage Jack-in-the-box is opened by a dying woman, she enters into a deal with the demon within that would see her illness cured in return for helping it claim six innocent victims.',
      popularity: 455.04,
      poster_path: '/3Ib8vlWTrAKRrTWUrTrZPOMW4jp.jpg',
      release_date: '2022-02-24',
      title: 'The Jack in the Box: Awakening',
      video: false,
      vote_average: 6.3,
      vote_count: 162,
    },
    {
      adult: false,
      backdrop_path: '/c7U9Fuy74WLp7gFAdpQJHn2T2no.jpg',
      genre_ids: [14, 28, 12, 10751],
      id: 81005,
      original_language: 'en',
      original_title: 'Jack the Giant Slayer',
      overview:
        'The story of an ancient war that is reignited when a young farmhand unwittingly opens a gateway between our world and a fearsome race of giants. Unleashed on the Earth for the first time in centuries, the giants strive to reclaim the land they once lost, forcing the young man, Jack into the battle of his life to stop them. Fighting for a kingdom, its people, and the love of a brave princess, he comes face to face with the unstoppable warriors he thought only existed in legend–and gets the chance to become a legend himself.',
      popularity: 61.976,
      poster_path: '/xLbVsFpAlwf6khU3gG1yaRBPeC.jpg',
      release_date: '2013-02-27',
      title: 'Jack the Giant Slayer',
      video: false,
      vote_average: 5.8,
      vote_count: 4428,
    },
    {
      adult: false,
      backdrop_path: '/ww1eIoywghjoMzRLRIcbJLuKnJH.jpg',
      genre_ids: [28, 53],
      id: 343611,
      original_language: 'en',
      original_title: 'Jack Reacher: Never Go Back',
      overview:
        'When Major Susan Turner is arrested for treason, ex-investigator Jack Reacher undertakes the challenging task to prove her innocence and ends up exposing a shocking conspiracy.',
      popularity: 62.876,
      poster_path: '/bvCEEs5l3ylNIgH4foqOmQk0qdi.jpg',
      release_date: '2016-10-19',
      title: 'Jack Reacher: Never Go Back',
      video: false,
      vote_average: 5.9,
      vote_count: 4153,
    },
  ],
};
